#!/usr/bin/env python3

import argparse
import threading
import time
from dataclasses import dataclass

try:
    from pynput import mouse, keyboard
except Exception:
    print("Missing dependency or unsupported environment. Install with: pip install -r requirements.txt")
    raise


@dataclass
class ClickConfig:
    click_multiplier: int = 5
    interval_between_clicks_seconds: float = 0.015
    enabled: bool = True
    toggle_hotkey: str = "<ctrl>+<alt>+m"
    quit_hotkey: str = "<ctrl>+<alt>+q"


class ClickMultiplier:
    def __init__(self, config: ClickConfig) -> None:
        self.config = config
        self._mouse_controller = mouse.Controller()
        self._lock = threading.RLock()
        self._running = True
        self._synthesizing = False  # Avoid reacting to our own synthetic clicks

    def _perform_extra_clicks(self, button: mouse.Button) -> None:
        with self._lock:
            if not self.config.enabled:
                return
            # Mark that we are emitting synthetic clicks to prevent recursion
            self._synthesizing = True
            try:
                for _ in range(max(0, self.config.click_multiplier - 1)):
                    self._mouse_controller.click(button)
                    time.sleep(max(0.0, self.config.interval_between_clicks_seconds))
            finally:
                self._synthesizing = False

    def on_click(self, _x: int, _y: int, button: mouse.Button, pressed: bool) -> None:
        if not pressed:
            return
        if button != mouse.Button.left:
            return
        with self._lock:
            if self._synthesizing:
                # Ignore clicks generated by ourselves
                return
            if not self.config.enabled:
                return
        threading.Thread(target=self._perform_extra_clicks, args=(button,), daemon=True).start()

    def toggle_enabled(self) -> None:
        with self._lock:
            self.config.enabled = not self.config.enabled
            state = "ON" if self.config.enabled else "OFF"
        print(f"[ClickMultiplier] Toggled: {state}")

    def quit(self) -> None:
        print("[ClickMultiplier] Quitting...")
        self._running = False

    def run(self) -> None:
        print("Click Multiplier is running.")
        print(f" - Multiplier: {self.config.click_multiplier}")
        print(f" - Interval: {self.config.interval_between_clicks_seconds}s")
        print(f" - Toggle: {self.config.toggle_hotkey}")
        print(f" - Quit:   {self.config.quit_hotkey}")

        hotkeys = keyboard.GlobalHotKeys({
            self.config.toggle_hotkey: self.toggle_enabled,
            self.config.quit_hotkey: self.quit,
        })

        with mouse.Listener(on_click=self.on_click) as mouse_listener, hotkeys:
            while self._running:
                time.sleep(0.1)
            mouse_listener.stop()


def parse_args() -> ClickConfig:
    parser = argparse.ArgumentParser(description="Multiply left mouse clicks.")
    parser.add_argument("--multiplier", type=int, default=5, help="Number of clicks per physical click (>=1)")
    parser.add_argument("--interval", type=float, default=0.015, help="Seconds between extra clicks")
    parser.add_argument("--toggle", type=str, default="<ctrl>+<alt>+m", help="Global hotkey to toggle on/off")
    parser.add_argument("--quit", type=str, default="<ctrl>+<alt>+q", help="Global hotkey to quit")
    args = parser.parse_args()

    multiplier = max(1, args.multiplier)
    interval = max(0.0, args.interval)
    return ClickConfig(
        click_multiplier=multiplier,
        interval_between_clicks_seconds=interval,
        enabled=True,
        toggle_hotkey=args.toggle,
        quit_hotkey=args.quit,
    )


def main() -> int:
    config = parse_args()
    app = ClickMultiplier(config)
    app.run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())